version: '3'

services:
  web:
    container_name: lighthouse_backend
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python3 manage.py collectstatic --noinput &&
             python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      - my-db
    volumes:
      - .:/code
    ports:
      - "8000:8000"
  my-db:
    container_name: my-db
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "6543:5432"

volumes:
  db_data: { }
